### ISSUE TITLE
网络灯闪蓝，风扇不转

### ISSUE THREAD

**Issue by ljw98** [mu2611/Lenovo-X1-shell#4]
群晖DSM 7.1.1-42962 Update 1
网络灯闪蓝，可以正常联网
test_temp.sh不能识别硬盘温度（可能就这个导致风扇不转）

**Comment by mu3517** [comment]
那你这个应该是有程序没copy到对应目录。 你打开install.sh 一行一行命令执行一次试试。 应该是缺少目录或者目录没权限。
