### ISSUE TITLE
X1S反馈

### ISSUE THREAD

**Issue by doa2011** [mu2611/Lenovo-X1-shell#9]
X1S，SA6400状态灯不正常，lan和硬盘均不亮灯
大佬，你用的是什么版本的群晖啊？另外想请教下，X1s带了个屏幕，是可以直接把screen文件夹移植过去么？

**Comment by doa2011** [comment]
提取x1s相关执行文件后，硬盘和lan指示灯正常了，另外可以监测的网卡需要自己改下！

**Comment by geekifan** [comment]
您好，请问您是否能够分享一下 x1s 的 screen 文件呢？我的 emmc 已经被清空了。感谢！

**Comment by doa2011** [comment]
> 您好，请问您是否能够分享一下 x1s 的 screen 文件呢？我的 emmc 已经被清空了。感谢！


[screen.zip](https://github.com/mu3517/Lenovo-X1-shell/files/14753519/screen.zip)
请问你研究了screen么？我搞不定驱动，自己编译又编译不成功，有其他思路可以探讨下

**Comment by geekifan** [comment]
非常感谢！请问关于其他的文件（控制 led 灯的和控制风扇）能否也帮忙上传一下～我发现 x1 的相关程序无法使用，谢谢～后续如果有任何相关的脚本研究我也会分享在这里

**Comment by geekifan** [comment]
等我看一下 screen 文件，我目前没有太多嵌入式开发经验，但理论上不会特别复杂，如果有进度我会及时分享

**Comment by doa2011** [comment]
> 非常感谢！请问关于其他的文件（控制 led 灯的和控制风扇）能否也帮忙上传一下～我发现 x1 的相关程序无法使用，谢谢～后续如果有任何相关的脚本研究我也会分享在这里

led灯，风扇之类的已经可以正常工作了，我温度控制是通过自己编译了个驱动加载到内核里面，加个V吧，可以讨论下，有成果了再放上来v：lee5233
